import React from 'react';
import redux from 'redux';
import { AppContainer } from 'react-hot-loader';
import {render, unmountComponentAtNode} from 'react-dom';
import configureStore, { history } from './app/store/configureStore'
import { Provider } from 'react-redux';
import axios from 'axios';
import {Card,CardActions,CardHeader, CardMedia, CardText,CardTitle} from 'material-ui/Card';
import { Switch, NavLink, Route } from 'react-router-dom';
import PropTypes from 'prop-types';
import darkBaseTheme from 'material-ui/styles/baseThemes/darkBaseTheme';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';
import AppBar from 'material-ui/AppBar';
import Drawer from 'material-ui/Drawer';
import MenuItem from 'material-ui/MenuItem';
import Subheader from 'material-ui/Subheader';
import CloseIcon from 'material-ui/svg-icons/navigation/close';
import IconButton from 'material-ui/IconButton';
import {List, ListItem } from 'material-ui/List';
